version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  lint:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run: npm install
      - run: npm run lint

  test:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run: npm install
      - run: npm run flow
      - run: npm run build --progress=false
      - run: npm run test

workflows:
  version: 2.1
  lint-and-test:
    jobs:
      - lint
      - test
