version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.14.0
    steps:
      - checkout
      - run: yarn install
      - run: yarn run lint
      - run: yarn run flow
      - run: yarn run build --progress=false
      - run: yarn run test
